name: setup-node
description: "Setup Node.js âš™ï¸ - Cache dependencies âš¡ - Install dependencies ğŸ”§"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js âš™ï¸
      uses: pnpm/action-setup@v4
      with:
        node-version: 24
        cache: true

    - name: Install dependencies ğŸ”§
      shell: bash
      run: pnpm install --frozen-lockfile